language: python
python:
  - 3.6
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853

matrix:
    include:
    - python: 3.5
      env:
        - PYTHON_VERSION="3.5"
        - DOC_BUILD="true"
    - python: 3.6
      env:
        - PYTHON_VERSION="3.6"
        - DOC_BUILD="true"
    env:
install:
    - source continuous_integration/install.sh
script:
    - eval xvfb-run pytest
    - flake8 --max-line-length=115
after_success:
    - source continuous_integration/build_docs.sh;
