name: testenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - proj
  - pyproj
  - numpy
  - scipy
  - matplotlib
  - netcdf4
  - pytest
  - pytest-mpl
  - pytest-cov
  - dask
  - xarray
  - astral
  - flake8
  - ipython
  - pint=0.8.1
  - pip:
    - mpl2nc
